r=int(input("Enter radius of circle : "))
print("Area of the circle = ",3.14*r*r)
l=int(input("Enter length of rectangle : "))
b=int(input("Enter bredth of rectangle : "))
print("Area of the rectangle = ",l*b)
h=int(input("Enter hight of Triangle : "))
tb=int(input("Enter bredth of Triangle : "))
print("Area of the Triangle = ",0.5*tb*h)
